baseURL: "https://sandvich.xyz/"
languageCode: "en-us"
title: "TheBatJam"
paginate: 5
theme: "thebatjam"
disqusShortname: "batjam"
summaryLength: 20


minify:
  disableXML: true
  minifyOutput: true

related:
  includeNewer: true
  indices:
  - name: tags
    weight: 5
  - name: type
    weight: 3
  - name: keywords
    weight: 2
  - name: date
    weight: 1
  - name: author
    weight: 1
  threshold: 45
  toLower: false

menu:
  main:
    - identifier: news
      name: news
      url: /category/news/
      weight: 1
    - identifier: guide
      name: guides
      url: /category/guide/
      weight: 2
    - identifier: opinion
      name: opinions
      url: /category/opinion/
      weight: 3
    - identifier: review
      name: reviews
      url: /category/review/
      weight: 4
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

taxonomies:
  category: category
  tag: tags

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

enableRobotsTXT: true
