baseURL: "http://sandvich.xyz/"
languageCode: "en-us"
title: "TheBatJam"
paginate: 5
theme: "thebatjam"
disqusShortname: "batjam"
summaryLength: 20

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

related:
  includeNewer: true
  indices:
  - name: tags
    weight: 5
  - name: categories
    weight: 3
  - name: keywords
    weight: 2
  - name: date
    weight: 1
  - name: author
    weight: 1
  threshold: 45
  toLower: false

menu:
  main:
    - identifier: news
      name: news
      url: /categories/news/
      weight: 1
    - identifier: guide
      name: guides
      url: /categories/guide/
      weight: 2
    - identifier: opinion
      name: opinions
      url: /categories/opinion/
      weight: 3
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
