---
title: "Why Forsen is Considered a Dead Streamer"
date: 2022-07-27T17:17:24-07:00
draft: true
category: ""
tags:
- forsen
- twitch
keywords:
- 
author: "John Jekyll"
cover: ""
---

In the early days of streaming, it was all about having fun. Some streamers
would have a few viewers and joke around with them for a bit. But by the middle
of 2018, things had taken a turn for the worst. With many streamers turning to
controversial tactics to garner popularity and stay relevant, the online video
platform known as Twitch quickly took notice. Twitch is an online video platform
owned by Amazon.com that allows users to live-stream video games in exchange for
money from viewers (affiliates).

While this may sound like a simple concept, the vast majority of streamers on
Twitch live-stream their content on location and broadcast 24 hours a day, 7
days a week; resulting in thousands of streams daily! To ensure that their
service stays relevant, many streamers are forced to rely on various methods
such as: advertising revenue, sponsorships or simply growing their follower
count & viewer base as fast as possible. One streamer in particular refused to
stay on many of Twitch's trends, eventually leading to the death of his
following and community.

* Who is Forsen?

The Twitch Streamer known as Forsen is a Swedish gamer who owned a small channel
with a modest following. It wasn't until the fall of 2018 that he started to
receive a lot of attention after he was featured on the popular video gaming
website, /r/LivestreamFail. Forsen was known for his epic /PlayerUnknown's
Battlegrounds/ clips, which saw an influx of new fans to his channel. Fosen's
growing popularity would cause him to be featured on many popular news websites
& blogs such as Kotaku, The Daily Dot, & Polygon.

* What is Trending on Twitch Right Now?

As the popularity of the Twitch Streamer, Forsen grew, so did the interest in
other content creators on Twitch. Since the majority of the community was still
new to Twitch, many of them would watch Twitch Streamers for hours on end,
looking for inspiration and tips on how to improve their content. With this in
mind, let’s take a look at some of the most popular & trending Twitch Channels
right now.

** Kripparrian - Hearthstone

One of the most popular Twitch Streamers at the moment is Kripparrian, who is a
well-known Hearthstone Streamer. Kripparrian has millions of subscribers and an
abolustely raging personality, so it’s no surprise that he’s so popular.

** xQc - Reacting

xQc is another legendary streamer from 2017. He is a well-known reaction
streamer, giving insightful takes in politics and humanities, establishing him
as the top streamer on Twitch.

** Sodapoppin - V-Tubing

Sodapoppin is a popular V-Tuber on Twitch. He first [[https://www.youtube.com/watch?v=S7yZoPB6d64][debuted as a V-Tuber on June
2021]]. Sodapoppin also recently joined OTK (One True King), a diverse
organization made up of several Twitch streamers around the world.

* Why did Forsen's channel die?

One of the biggest factors for why Forsen's Twitch channel failed was because he
didn't take advantage of Twitch's latest trends at the time. While he did
attempt to follow a few trends such as the "reaction" trend, he never really
gained any traction from it.

In addition, he continues to play the same games such as PUBG instead of trying
out other trendy games such as /Valorant/. Many of his viewers engage in what is
known as "stream sniping" where his audience attempt to locate his exact
position based on his stream. Forsen has never attempted to mitigate any stream
sniper activity, resulting in his streams becoming less appealing to new
viewers.

As a result, his channel died as it did not capture the attention of new
viewers. By simply updating his Twitch channel to match the latest trends and
pumping out new videos on a regular basis and keeping his name in the front of
viewers' minds, Forsen could have kept his channel alive long enough to build up
an audience of loyal followers.
