# This is a basic workflow that is manually triggered

name: Deploy master to sandvich.xyz

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Building website from master
      uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify
    - name: Deploying to sandvich.xyz
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: ./public/
        remote_path: /data/websites/thebatjam/public/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: 2200
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
